/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppAdMobConfig {
  'appId' : string,
  'rewardedAdUnitId' : string,
}
export interface AppLogo { 'file' : ExternalBlob, 'mediaType' : string }
export interface AppMetrics {
  'installs' : bigint,
  'blockedCount' : bigint,
  'activeCount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface SessionInfo { 'unlockExpiresAt' : Time }
export type Time = bigint;
export interface UserOverview {
  'userStatuses' : Array<[Principal, UserStatus]>,
  'userProfiles' : Array<[Principal, UserProfile]>,
  'sessions' : Array<[Principal, SessionInfo]>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'blocked' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'clearSessions' : ActorMethod<[], undefined>,
  'getAllSessions' : ActorMethod<[], Array<SessionInfo>>,
  'getAppAdMobConfig' : ActorMethod<[], [] | [AppAdMobConfig]>,
  'getAppAdMobConfigPublic' : ActorMethod<[], [] | [AppAdMobConfig]>,
  'getAppMetrics' : ActorMethod<[], AppMetrics>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLogo' : ActorMethod<[], [] | [AppLogo]>,
  'getSessions' : ActorMethod<[], SessionInfo>,
  'getUserOverview' : ActorMethod<[], UserOverview>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementInstalls' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCurrentPrincipalAdmin' : ActorMethod<[], boolean>,
  'isUserBlocked' : ActorMethod<[Principal], boolean>,
  'makeCurrentPrincipalAdmin' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAppAdMobConfig' : ActorMethod<[AppAdMobConfig], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'unlockSessions' : ActorMethod<[], undefined>,
  'uploadLogo' : ActorMethod<[AppLogo], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];