/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const SessionInfo = IDL.Record({ 'unlockExpiresAt' : Time });
export const AppAdMobConfig = IDL.Record({
  'appId' : IDL.Text,
  'rewardedAdUnitId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearSessions' : IDL.Func([], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(SessionInfo)], ['query']),
  'getAppAdMobConfig' : IDL.Func([], [IDL.Opt(AppAdMobConfig)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSessions' : IDL.Func([], [SessionInfo], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCurrentPrincipalAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeCurrentPrincipalAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAppAdMobConfig' : IDL.Func([AppAdMobConfig], [], []),
  'unlockSessions' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const SessionInfo = IDL.Record({ 'unlockExpiresAt' : Time });
  const AppAdMobConfig = IDL.Record({
    'appId' : IDL.Text,
    'rewardedAdUnitId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearSessions' : IDL.Func([], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(SessionInfo)], ['query']),
    'getAppAdMobConfig' : IDL.Func([], [IDL.Opt(AppAdMobConfig)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSessions' : IDL.Func([], [SessionInfo], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCurrentPrincipalAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeCurrentPrincipalAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAppAdMobConfig' : IDL.Func([AppAdMobConfig], [], []),
    'unlockSessions' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };