/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const SessionInfo = IDL.Record({ 'unlockExpiresAt' : Time });
export const AppAdMobConfig = IDL.Record({
  'appId' : IDL.Text,
  'rewardedAdUnitId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AppLogo = IDL.Record({
  'file' : ExternalBlob,
  'mediaType' : IDL.Text,
});
export const UserOverview = IDL.Record({
  'userProfiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
  'sessions' : IDL.Vec(IDL.Tuple(IDL.Principal, SessionInfo)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearSessions' : IDL.Func([], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(SessionInfo)], ['query']),
  'getAppAdMobConfig' : IDL.Func([], [IDL.Opt(AppAdMobConfig)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLogo' : IDL.Func([], [IDL.Opt(AppLogo)], ['query']),
  'getSessions' : IDL.Func([], [SessionInfo], ['query']),
  'getUserOverview' : IDL.Func([], [UserOverview], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCurrentPrincipalAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeCurrentPrincipalAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAppAdMobConfig' : IDL.Func([AppAdMobConfig], [], []),
  'unlockSessions' : IDL.Func([], [], []),
  'uploadLogo' : IDL.Func([AppLogo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const SessionInfo = IDL.Record({ 'unlockExpiresAt' : Time });
  const AppAdMobConfig = IDL.Record({
    'appId' : IDL.Text,
    'rewardedAdUnitId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AppLogo = IDL.Record({ 'file' : ExternalBlob, 'mediaType' : IDL.Text });
  const UserOverview = IDL.Record({
    'userProfiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
    'sessions' : IDL.Vec(IDL.Tuple(IDL.Principal, SessionInfo)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearSessions' : IDL.Func([], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(SessionInfo)], ['query']),
    'getAppAdMobConfig' : IDL.Func([], [IDL.Opt(AppAdMobConfig)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLogo' : IDL.Func([], [IDL.Opt(AppLogo)], ['query']),
    'getSessions' : IDL.Func([], [SessionInfo], ['query']),
    'getUserOverview' : IDL.Func([], [UserOverview], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCurrentPrincipalAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeCurrentPrincipalAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAppAdMobConfig' : IDL.Func([AppAdMobConfig], [], []),
    'unlockSessions' : IDL.Func([], [], []),
    'uploadLogo' : IDL.Func([AppLogo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };